// Opt-in operational capability packs. Kept separate from auto-detected
// application-stack profiles so hosts receive this broad knowledge only when asked.

export const CAPABILITY_PACKS = {
  "devops-platform": {
    "label": "DevOps platform",
    "description": "CI/CD, containers, Kubernetes, observability, AI pipelines, developer environments, and release operations.",
    "skills": [
      "ai-pipeline-orchestration",
      "alerting-oncall",
      "argocd-gitops",
      "blue-green-deploy",
      "container-registries",
      "devcontainers-nix",
      "docker-compose",
      "docker-management",
      "feature-flags",
      "git-workflow",
      "github-actions",
      "gitlab-ci",
      "helm-charts",
      "kubernetes-ops",
      "kustomize",
      "llm-caching",
      "llm-cost-optimization",
      "loki-logging",
      "opentelemetry",
      "podman",
      "prometheus-grafana",
      "semantic-versioning"
    ]
  },
  "security": {
    "label": "Security",
    "description": "Defensive scanning, secrets, hardening, network security, incident response, and AI security.",
    "skills": [
      "ai-agent-security",
      "ai-coding-agent-guardrails",
      "ai-red-teaming",
      "ai-security-hardening",
      "aws-secrets-manager",
      "azure-keyvault",
      "cis-benchmarks",
      "container-hardening",
      "container-scanning",
      "dast-scanning",
      "dependency-scanning",
      "firewall-config",
      "gcp-secret-manager",
      "hashicorp-vault",
      "incident-response",
      "kubernetes-hardening",
      "linux-hardening",
      "llm-app-security",
      "mcp-server-security",
      "model-supply-chain-security",
      "openclaw-deployment-hardening",
      "penetration-testing",
      "prompt-injection-defense",
      "sast-scanning",
      "sbom-supply-chain",
      "security-automation",
      "sops-encryption",
      "ssl-tls-management",
      "supply-chain-attack-response",
      "threat-modeling",
      "vpn-setup",
      "vulnerability-scanning",
      "waf-setup",
      "windows-hardening",
      "zero-trust"
    ]
  },
  "infrastructure": {
    "label": "Infrastructure",
    "description": "Cloud, IaC, servers, networking, databases, storage, platforms, IT, and AI infrastructure operations.",
    "skills": [
      "ai-inference-service-mesh",
      "arm-templates",
      "aws-cost-optimization",
      "aws-ec2",
      "aws-ecs-fargate",
      "aws-iam",
      "aws-lambda",
      "aws-rds",
      "aws-s3",
      "aws-vpc",
      "azure-aks",
      "azure-functions",
      "azure-networking",
      "azure-sql",
      "azure-vms",
      "backup-recovery",
      "block-storage",
      "cdn-setup",
      "cloudflare-pages",
      "cloudflare-r2",
      "cloudflare-workers",
      "cloudflare-zero-trust",
      "cloudformation",
      "convex-backend",
      "database-backups",
      "dns-management",
      "firebase-app-platform",
      "gcp-cloud-functions",
      "gcp-cloud-sql",
      "gcp-compute",
      "gcp-gke",
      "gcp-networking",
      "gpu-kubernetes-operations",
      "gpu-server-management",
      "identity-access-management",
      "linux-administration",
      "llm-fine-tuning",
      "llm-gateway",
      "llm-inference-scaling",
      "load-balancing",
      "mac-mini-llm-lab",
      "mdm-device-management",
      "mongodb",
      "multi-tenant-llm-hosting",
      "mysql",
      "nfs-storage",
      "object-storage",
      "ollama-stack",
      "openclaw-local-mac-mini",
      "openclaw-security-hardening",
      "opentofu-migration",
      "performance-tuning",
      "planetscale",
      "postgresql",
      "rag-infrastructure",
      "redis",
      "reverse-proxy",
      "saas-security-posture",
      "service-mesh",
      "ssh-configuration",
      "startup-it-troubleshooting",
      "systemd-services",
      "terraform-aws",
      "terraform-azure",
      "terraform-gcp",
      "user-management",
      "vector-database-ops",
      "vercel-deployments",
      "vllm-server",
      "windows-server"
    ]
  },
  "compliance": {
    "label": "Compliance",
    "description": "Framework mapping, governance, evidence, continuity, auditing, and incident management.",
    "skills": [
      "access-review",
      "asset-inventory",
      "audit-logging",
      "aws-cloudtrail",
      "azure-monitor-audit",
      "business-continuity",
      "change-management",
      "disaster-recovery",
      "fedramp-compliance",
      "gcp-audit-logs",
      "gdpr-compliance",
      "hipaa-compliance",
      "incident-management",
      "iso27001-compliance",
      "pci-dss-compliance",
      "policy-as-code",
      "runbook-creation",
      "soc2-compliance",
      "vendor-management"
    ]
  }
}

export const selectCapabilityPacks = (ids) => {
  const unknown = ids.filter((id) => !CAPABILITY_PACKS[id])
  if (unknown.length) throw new Error(`Unknown capability pack(s): ${unknown.join(", ")}`)
  return [...new Set(ids.flatMap((id) => CAPABILITY_PACKS[id].skills))]
}
